[package]
name = "requiem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
nannou = "0.18.1"
regex = "1.8.4"
